name: CI

on: push

jobs:

  build:

    name: Build
    runs-on: ubuntu-24.04
    container: registry.gitlab.com/islandoftex/images/texlive:TL2025-2025-02-21-full

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Git safe.directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Lint
        run: make chktex

      - name: Compile to PostScript
        run: make gfkg.ps && make clean

      - name: Compile to PDF
        run: make

      - name: Print log
        run: cat gfkg.log
        if: always()

      - name: Hash
        run: sha256sum gfkg.pdf gfkg.ps | tee gfkg.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gfkg
          path: |
            gfkg.pdf
            gfkg.ps
            gfkg.log
            gfkg.sha256
          if-no-files-found: error

      - name: Clean up
        run: make cleanall

  release:

    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: gfkg

      - name: Check integrity
        run: sha256sum -c --strict gfkg.sha256

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            gfkg.pdf
            gfkg.ps
            gfkg.sha256
          generate_release_notes: true
          fail_on_unmatched_files: true

  publish:

    name: Publish
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-24.04

    permissions:
      pages: write
      id-token: write
      contents: read

    environment:
      name: pages
      url: ${{ steps.publish.outputs.page_url }}

    concurrency:
      group: pages

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          name: gfkg
          path: site

      - name: Check integrity
        run: sha256sum -c --strict gfkg.sha256
        working-directory: ${{ steps.download.outputs.download-path }}

      - name: Render Markdown
        id: markdown
        uses: fionn/render-markdown@v0.0.6
        with:
          token: ${{ github.token }}

      - name: Write index.html
        run: |
          echo '${{ steps.markdown.outputs.html }}' \
            >  ${{ steps.download.outputs.download-path }}/index.html

      - name: Upload tarball
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.download.outputs.download-path }}

      - name: Publish
        id: publish
        uses: actions/deploy-pages@v4
